<a href="https://colab.research.google.com/github/HyeranYang/Projects_Senior_IT_Support_Center/blob/master/%EC%A3%BC%EC%86%8C_%EC%9C%84%EB%8F%84%2C%EA%B2%BD%EB%8F%84_utmk_%EB%B3%80%ED%99%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- 주민센터 주소를 이용해 위도, 경도를 가져옴.
- 지오코딩 이용
- 거리계산을 위해 WGS84(위도, 경도) 좌표계를 UTMK 좌표계로 변환

# Imports

In [ ]:
import pandas as pd
!pip install geopy
from geopy.geocoders import Nominatim

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: geopy in /usr/local/lib/python3.7/dist-packages (1.17.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /usr/local/lib/python3.7/dist-packages (from geopy) (1.52)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/PROJECT_senior it support center/데이터/주민센터 주소.csv')
df.head()

   Unnamed: 0         주민센터명                 주소
0           0    청운효자동 주민센터  서울특별시 종로구 자하문로 92
1           1      사직동 주민센터  서울특별시 종로구 사직로9길 1
2           2  종로1-4가동 주민센터  서울특별시 종로구 종로17길 8
3           3      삼청동 주민센터  서울특별시 종로구 삼청로 107
4           4      가회동 주민센터   서울특별시 종로구 북촌로 35

In [ ]:
geolocoder = Nominatim(user_agent = 'South Korea', timeout=None)

def geocoding(address):
    try :
        geo = geolocoder.geocode(address)
        crd = (str(geo.latitude), str(geo.longitude))
        return crd
    except :
        return (0, 0)

In [ ]:
lats = []
logs = []

for address in df['주소'] :
    crd = geocoding(address)

    lats.append(crd[0])
    logs.append(crd[1])

lats = pd.Series(lats)
logs = pd.Series(logs)

In [ ]:
lats

0              37.5840835
1      37.576191449999996
2              37.5707276
3              37.5849793
4             37.58002545
              ...
419            37.5248662
420            37.5460139
421            37.5538754
422            37.5395191
423            37.5649416
Length: 424, dtype: object

In [ ]:
df = pd.concat([df, lats], axis=1)
df = pd.concat([df, logs], axis=1)
df.head()

,Unnamed: 0,주민센터명,주소,0,0
0,0,청운효자동 주민센터,서울특별시 종로구 자하문로 92,37.5840835,126.9706357
1,1,사직동 주민센터,서울특별시 종로구 사직로9길 1,37.576191449999996,126.96882915
2,2,종로1-4가동 주민센터,서울특별시 종로구 종로17길 8,37.5707276,126.9889123
3,3,삼청동 주민센터,서울특별시 종로구 삼청로 107,37.5849793,126.98178162729107
4,4,가회동 주민센터,서울특별시 종로구 북촌로 35,37.58002545,126.98480464831948

In [ ]:
df.drop(columns='Unnamed: 0', inplace=True)
df.head()

          주민센터명                 주소                   0                   0
0    청운효자동 주민센터  서울특별시 종로구 자하문로 92          37.5840835         126.9706357
1      사직동 주민센터  서울특별시 종로구 사직로9길 1  37.576191449999996        126.96882915
2  종로1-4가동 주민센터  서울특별시 종로구 종로17길 8          37.5707276         126.9889123
3      삼청동 주민센터  서울특별시 종로구 삼청로 107          37.5849793  126.98178162729107
4      가회동 주민센터   서울특별시 종로구 북촌로 35         37.58002545  126.98480464831948

In [ ]:
df.columns=['시설명', '주소', '위도', '경도']

In [ ]:
df.head()

            시설명                 주소                  위도                  경도
0    청운효자동 주민센터  서울특별시 종로구 자하문로 92          37.5840835         126.9706357
1      사직동 주민센터  서울특별시 종로구 사직로9길 1  37.576191449999996        126.96882915
2  종로1-4가동 주민센터  서울특별시 종로구 종로17길 8          37.5707276         126.9889123
3      삼청동 주민센터  서울특별시 종로구 삼청로 107          37.5849793  126.98178162729107
4      가회동 주민센터   서울특별시 종로구 북촌로 35         37.58002545  126.98480464831948

In [ ]:
# 변환되지 않은 관측치들 확인
df[df['위도']==0]

           시설명                   주소 위도 경도
115   안암동 주민센터     서울특별시 성북구 인촌로 16  0  0
238  신정6동 주민센터     서울특별시 양천구 신남3길 6  0  0
274   수궁동 주민센터  서울특별시 구로구 오리로15길 32  0  0

In [ ]:
# 주소는 제대로 되어있음 gmap에서 찾아 직접 넣어주기.

# 안암동 주민센터
df.iloc[115, 2]= 37.5858
df.iloc[115, 3]= 127.0214

#신정6동 주민센터
df.iloc[238, 1]= '서울특별시 양천구 목동서로 353' # 주소 수정
df.iloc[238, 2]= 37.5171
df.iloc[238, 3]= 126.8645

# 수궁동 주민센터
df.iloc[274, 2]= 37.4939
df.iloc[274, 3]= 126.8315

In [ ]:
# 확인작업 
df[df['위도']==0] # 위도 경도 모두 변환 완료

Empty DataFrame
Columns: [시설명, 주소, 위도, 경도]
Index: []

# 주민센터 UTMK 추가

In [ ]:
!pip install pyproj

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyproj
  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 28.0 MB/s
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from pyproj) (2022.9.24)
Installing collected packages: pyproj
Successfully installed pyproj-3.2.1

In [ ]:
import pandas as pd
import numpy as np
import pyproj
from pyproj import Transformer

In [ ]:
df.head()

            시설명                 주소                  위도                  경도
0    청운효자동 주민센터  서울특별시 종로구 자하문로 92          37.5840835         126.9706357
1      사직동 주민센터  서울특별시 종로구 사직로9길 1  37.576191449999996        126.96882915
2  종로1-4가동 주민센터  서울특별시 종로구 종로17길 8          37.5707276         126.9889123
3      삼청동 주민센터  서울특별시 종로구 삼청로 107          37.5849793  126.98178162729107
4      가회동 주민센터   서울특별시 종로구 북촌로 35         37.58002545  126.98480464831948

In [ ]:
# 서울역 위도, 경도((37.553230, 126.972551) (예시)
transformer = Transformer.from_crs("epsg:4326", "epsg:5178")
transformer.transform(37.553230, 126.972551)

(1950256.3879044417, 953600.9747718363)

In [ ]:
# transformer.transform(37.560927, 127.193877)
list_utmk = []
for i in range(len(df)):
    list_utmk.append(transformer.transform(df['위도'][i], df['경도'][i]))

list_utmk

[(1953680.4107067548, 953451.0305672353),
 (1952805.715076733, 953286.5880716629),
 (1952189.7125275738, 955056.6789118368),
 (1953774.3237514033, 954435.6795061507),
 (1953223.248442944, 954699.5803852201),
 (1952327.4588193654, 956483.9647044425),
 (1952875.5529025472, 956420.6357743395),
 (1953970.565093043, 956098.4625721083),
 (1952829.6012131637, 957408.6513756055),
 (1952721.4395271284, 957004.4189000049),
 (1952829.6012131637, 957408.6513756055),
 (1952829.6012131637, 957408.6513756055),
 (1952732.1914813584, 957802.5274845127),
 (1952330.4399108805, 952675.5729051178),
 (1956152.3522304904, 953258.8070320927),
 (1954369.3167579314, 953453.7461930809),
 (1952786.0967898367, 952346.0677775362),
 (1951327.7279225483, 954026.6687767816),
 (1950706.6244977568, 954198.7293203992),
 (1951005.4741406671, 954779.2664321188),
 (1951051.0375977478, 955569.7448418225),
 (1951201.9229545821, 956713.4114992636),
 (1951123.2482809008, 954856.312150551),
 (1951799.2587764326, 955177.7516927773),
 (1950359.1484195068, 956759.5967588911),
 (1950848.1859842215, 957773.5799129383),
 (1951547.023979897, 957962.2354495099),
 (1949967.7260796265, 956699.237030841),
 (1950154.2305403461, 956820.5194565757),
 (1950662.1298788488, 957326.3972910652),
 (1951810.569643312, 957921.050483988),
 (1950970.0813317406, 953115.723533471),
 (1950284.9569045305, 953795.7552509106),
 (1949462.0954675837, 954746.7973257231),
 (1949424.9859067355, 953797.5203467604),
 (1949393.3329406723, 953346.485128354),
 (1948117.5510571564, 951761.4710612055),
 (1949067.2424600925, 952652.3476385667),
 (1948528.429421103, 951902.905858693),
 (1948487.6238336258, 953165.0783507226),
 (1947472.1623853028, 953289.3322292849),
 (1946698.191024135, 953608.561874259),
 (1947265.3714448237, 952048.8781844992),
 (1947576.5565723332, 955838.0046750326),
 (1948967.1914697597, 955191.3000937442),
 (1948178.664397065, 956060.163592259),
 (1946585.2464665854, 955167.1592111429),
 (1947391.6457821415, 955566.5364465291),
 (1951863.9694967784, 958294.0466677527),
 (1950943.3240207322, 958297.3636838844),
 (1951626.1847433723, 960073.3198211242),
 (1951073.7605905798, 960052.9936140279),
 (1950839.2210213149, 959164.1508572883),
 (1950784.444723976, 958620.78807751),
 (1949417.9173437685, 957608.1838144304),
 (1950782.5206016102, 958907.1813354607),
 (1950158.2607254102, 957979.4736869485),
 (1949512.5022576852, 957827.6591910698),
 (1949668.533954076, 958441.9181677887),
 (1948982.591150884, 960404.5249443939),
 (1949439.8774585165, 959957.8311428023),
 (1948686.5462296885, 960694.3915547535),
 (1949718.803866381, 960830.3838307335),
 (1950399.9294559609, 962181.2936761463),
 (1951465.2392800471, 960940.069118924),
 (1951119.4122565305, 963122.0840865667),
 (1951590.5839046799, 963467.8968519723),
 (1951939.5677563462, 963115.3845274539),
 (1950853.7108070506, 963932.1257632754),
 (1950357.7099021787, 963165.1021547364),
 (1949132.1527887979, 963652.4792664221),
 (1949599.0561627946, 963997.3434273849),
 (1948518.7783140175, 964145.0085614767),
 (1949314.417649033, 964757.2240524868),
 (1948002.508628861, 963242.6993568022),
 (1947590.8171164526, 963456.1861042405),
 (1948060.5604262243, 962454.0857652037),
 (1948264.3591906214, 961762.0343676662),
 (1949449.0016137674, 962456.2197899709),
 (1949366.0847791233, 962266.8685367088),
 (1952731.8773391175, 959331.4653420344),
 (1953541.9519788052, 959384.6478781768),
 (1952968.263187675, 960248.090639698),
 (1952977.742582705, 961339.2845891509),
 (1952084.1004872485, 960464.5273392434),
 (1951788.7949288343, 961447.4564641513),
 (1951833.3693640372, 961901.7004203752),
 (1953014.9595468827, 962274.0066901149),
 (1953886.3581902513, 960218.9292270496),
 (1954384.453191264, 960938.4022971926),
 (1954618.6650603728, 961856.8109370052),
 (1954306.8555901118, 962105.612091342),
 (1954465.552750057, 961982.9624624315),
 (1955737.6819132562, 961772.522638597),
 (1954262.3224504772, 963025.2587191451),
 (1953503.897413822, 963820.1043174323),
 (1954990.7235113669, 963600.0867660377),
 (1955246.8580785638, 963056.9787100377),
 (1954990.7235113669, 963600.0867660377),
 (1953992.794825262, 963770.7590400426),
 (1955242.5516424759, 963810.5426809648),
 (1954893.6418290702, 964592.7252614299),
 (1955524.6089551977, 963172.1145533985),
 (1955865.9508991959, 962774.6919473538),
 (1956887.0877412837, 963012.3093197806),
 (1956465.2320530615, 962768.9947073418),
 (1956920.1955824955, 965010.9360824414),
 (1955452.1675824882, 965013.4927016956),
 (1956048.0723749571, 964841.5821766633),
 (1956086.2333341937, 964372.1796668917),
 (1954828.756920148, 955599.607829827),
 (1955889.246235471, 958416.7121408652),
 (1955207.3804860592, 956984.8652249743),
 (1954410.580029217, 957342.0824290671),
 (1954755.6581197262, 957853.6243144197),
 (1953846.869634162, 957934.1030066017),
 (1953185.3902561483, 958107.3509177173),
 (1955583.2323181953, 957526.306817905),
 (1955922.8170094183, 957040.2219441368),
 (1956378.2714229117, 956402.6674466496),
 (1956520.874462604, 956900.4357787335),
 (1955886.3547547439, 958175.9035877064),
 (1956054.6798559448, 958278.4315146853),
 (1955370.040203173, 959072.661560796),
 (1956587.995075793, 959215.4966904483),
 (1956098.1993009474, 960302.3273510666),
 (1956937.7878135387, 959516.417561368),
 (1956667.300624078, 960776.924940061),
 (1957836.5443812085, 960642.4442735022),
 (1956098.1993009474, 960302.3273510666),
 (1958424.747417023, 958457.5628655386),
 (1957140.3891924943, 957965.6510741217),
 (1958457.1451982628, 957691.6749946657),
 (1957206.3138728132, 959044.0852222869),
 (1957452.4251141283, 958170.0174417372),
 (1959617.990559452, 958618.9982377721),
 (1959194.7024972872, 959375.6307971921),
 (1958200.8835975658, 960024.154772832),
 (1962329.3432046156, 957243.036938735),
 (1959194.7024972872, 959375.6307971921),
 (1959814.7999509482, 958076.1906994741),
 (1960749.2457782952, 957101.0547012828),
 (1960029.2131793897, 957015.3446989566),
 (1961254.1765445524, 960710.3308665538),
 (1961849.5953753884, 959514.5368401301),
 (1960719.4970868737, 958715.3421920867),
 (1961493.0110450287, 958550.8218334002),
 (1962528.180492255, 959609.115296876),
 (1961844.9038583953, 958541.3854777503),
 (1961982.7069324076, 958559.6165665971),
 (1960655.182756086, 960036.8713244813),
 (1959952.315607049, 959512.7455639176),
 (1959721.1279678864, 959801.7121932852),
 (1961207.2069111727, 960625.0870812433),
 (1961664.1170901104, 959933.7670306123),
 (1963795.2776785686, 959943.7292586284),
 (1963139.7583146668, 960196.5903431393),
 (1957623.297896414, 961643.9961343262),
 (1958993.2774529923, 960436.11947338),
 (1959213.354091355, 961372.5510512),
 (1958151.5334729808, 962583.0280045029),
 (1957795.294610629, 963551.3404497395),
 (1961760.3108967252, 961946.3405627885),
 (1958950.0143569936, 962067.5984111185),
 (1961760.3108967252, 961946.3405627885),
 (1964267.8584594259, 960940.3442986927),
 (1961926.2999988887, 962149.705337611),
 (1963487.4018681855, 963438.2044433191),
 (1961931.5639398422, 962589.2670726527),
 (1961488.884368537, 961996.7818728462),
 (1962872.7169148216, 960849.9019480281),
 (1962561.0696594568, 961720.5106426608),
 (1961228.6571031276, 962918.2753650027),
 (1960076.4192666572, 962139.4096991544),
 (1961918.8854613276, 962967.6121603535),
 (1961016.5360951268, 962962.0745800359),
 (1954909.5219719731, 948138.4018768917),
 (1955222.51320941, 948140.5217502625),
 (1956618.7354582946, 950067.3326418954),
 (1958396.0250624944, 949647.2221706748),
 (1958098.7667348925, 948713.1614831799),
 (1957545.2018541559, 948631.750078259),
 (1956718.8507109568, 948118.8445387394),
 (1957036.6396676428, 948935.4660771216),
 (1954793.8834865948, 949262.1060271101),
 (1954873.9815739458, 949260.7758507116),
 (1954613.4781864546, 948610.6367486243),
 (1958422.1364143216, 949814.4214405318),
 (1955233.2306388125, 948266.5115287175),
 (1954408.6070367733, 948041.64364434),
 (1953744.3787386112, 947834.7001182113),
 (1959344.59622061, 949108.6967615368),
 (1951488.1268655695, 949886.5451079557),
 (1950952.5062588342, 952230.6324317944),
 (1951548.949266295, 952031.8622584448),
 (1953880.4156038833, 951400.5947531434),
 (1953915.6175203647, 951575.3041594297),
 (1954766.6545248758, 951610.7827802985),
 (1950925.8233716507, 950986.5323782368),
 (1951707.392776517, 949819.5309566703),
 (1955331.6596886464, 951389.0464262228),
 (1953262.9822769677, 950229.976354613),
 (1952958.9672601537, 947455.4985777657),
 (1953442.6982573129, 948130.5144940517),
 (1952638.4472497026, 948841.0267731824),
 (1953078.5546829088, 949319.5194203447),
 (1949923.842509848, 952495.327738771),
 (1949588.2915706008, 951798.4854807402),
 (1948995.4355996693, 951717.9497453175),
 (1949113.8647386688, 951047.5309019377),
 (1949544.1324952992, 951195.3804480715),
 (1950502.2154246112, 950954.8703871093),
 (1949610.708673312, 950656.1432948866),
 (1949610.708673312, 950656.1432948866),
 (1950571.5788030284, 948454.9171754696),
 (1949940.8871033306, 947688.5389233615),
 (1950585.319931934, 947748.5253895677),
 (1951158.1545958787, 947371.9200522926),
 (1951623.5141444404, 949149.6245886957),
 (1951407.8333153042, 947894.3245355027),
 (1951994.0247106622, 947997.6709260917),
 (1953083.719815924, 946741.4346658053),
 (1946548.396251793, 943416.4379081451),
 (1946536.8603467746, 944579.0733417111),
 (1946095.3168386878, 943171.9703020662),
 (1947080.1109361837, 943529.8320838521),
 (1946303.0408787613, 944027.7214576479),
 (1946193.7779695182, 944104.1247324198),
 (1946095.3168386878, 943171.9703020662),
 (1947769.5078645705, 944634.4772110535),
 (1949522.95581529, 944687.4748733855),
 (1949370.3553490138, 944046.9487234314),
 (1948002.7908635861, 944382.569872236),
 (1948526.3742028181, 945567.1318883692),
 (1948038.3311371512, 941134.140781443),
 (1947308.8781011605, 942507.000212088),
 (1948056.716937402, 940843.7226257373),
 (1948618.9187730947, 940822.2401521628),
 (1946306.8041360513, 944029.8895867992),
 (1946848.1614068486, 941464.1442636424),
 (1950334.2961575699, 944651.0423548328),
 (1950471.3805970787, 943593.2746823155),
 (1950071.6407838473, 944014.692788933),
 (1950950.915784211, 942598.6011897648),
 (1949788.7778165047, 942044.3628386261),
 (1947805.6133977717, 942014.8081878242),
 (1948058.6441819624, 943201.2863087583),
 (1949144.0615739275, 941746.228836856),
 (1948109.1424168204, 943756.1960621756),
 (1951373.181496181, 943317.0866846202),
 (1947903.40912948, 942678.8506174552),
 (1949304.6460141016, 942566.8044738688),
 (1952128.5852490705, 942320.8062157248),
 (1951653.959470234, 943101.1753972914),
 (1951653.959470234, 943101.1753972914),
 (1950325.160974402, 941301.6090078218),
 (1950885.83256031, 939345.4820120246),
 (1952098.7606144077, 939508.9779950281),
 (1951848.0153101012, 938967.4605943736),
 (1953177.602392575, 939576.3490403675),
 (1945166.022783797, 945283.7107149237),
 (1942262.3374814633, 946783.4081937481),
 (1943501.4420250393, 945032.7538287038),
 (1942862.4684589775, 945866.6325196255),
 (1942996.7248846912, 946297.4165019826),
 (1943462.3527255105, 946187.6239921139),
 (1944493.5034927449, 946289.608082893),
 (1944407.3404270401, 943870.6259526461),
 (1945169.2844528975, 943243.143067485),
 (1944603.6090683627, 942790.8359579839),
 (1943358.6479389782, 943326.3170253469),
 (1942875.4368683489, 942848.2461009814),
 (1943491.6154205834, 941157.3138883539),
 (1943603.0480698105, 941901.1064103469),
 (1943753.0330205306, 941095.363355414),
 (1941215.3803985044, 946987.73589295),
 (1941087.496146096, 946901.4436588347),
 (1940736.613479538, 947109.6689295433),
 (1941628.638555244, 947422.8530162094),
 (1940465.2542206512, 947375.643278691),
 (1939230.3758876235, 947410.1428686206),
 (1938789.61161841, 948395.5275658339),
 (1937761.1528216104, 947627.2326468463),
 (1940028.2214074226, 947864.6684812282),
 (1939082.6073380243, 947837.9400192681),
 (1945981.8541769565, 948050.8877996417),
 (1946445.2754202723, 948229.2702984741),
 (1946335.533766878, 950227.1650472241),
 (1947127.8626379615, 946961.7837789827),
 (1946431.5896087266, 946714.8903093766),
 (1945388.180993731, 946813.8330115872),
 (1946259.0110970333, 947097.7050711442),
 (1947058.6734706298, 946121.0825052548),
 (1948684.662792328, 946864.4396180141),
 (1945600.6913744009, 949105.5834708416),
 (1945241.5007157405, 947836.3125488281),
 (1945063.3563450268, 948450.0576081974),
 (1944564.4574359902, 947619.6306348355),
 (1944314.131206603, 948025.4117304846),
 (1945085.4165773713, 949055.536261726),
 (1943581.580171224, 947472.5654123152),
 (1943585.231729968, 946997.0272408073),
 (1944201.3071758542, 946982.2073556194),
 (1945732.1055755743, 950877.0512254388),
 (1945314.1913866673, 950460.0097062832),
 (1944145.867545478, 951842.9426169035),
 (1944968.5893853868, 950897.4783431183),
 (1944273.7837671568, 949927.0619637073),
 (1944468.6434324305, 950486.1166439806),
 (1944997.7319230603, 953049.1044472137),
 (1942464.2160973207, 954107.3477499762),
 (1943087.115254528, 954153.74774289),
 (1942871.490526842, 953515.1288727326),
 (1942238.0813769838, 953477.7766839741),
 (1942757.5571066118, 953069.0977399247),
 (1945274.477254538, 949482.8297867031),
 (1943155.9464032324, 948035.4338726384),
 (1944275.143552726, 949455.1306093105),
 (1941725.6974905934, 952302.700465944),
 (1942447.8736453354, 951425.4420721269),
 (1943188.108085128, 951408.7444580738),
 (1942729.3444192107, 950894.7788786376),
 (1941593.2702219316, 952905.0722220569),
 (1942599.7896867436, 951546.1571150778),
 (1942048.109105611, 950821.698729496),
 (1943450.3012338332, 952330.223168192),
 (1942209.1537821242, 952187.7724709733),
 (1941152.021075628, 949048.1794169777),
 (1940111.0231585256, 948784.520188452),
 (1940840.6480232049, 951254.1858275363),
 (1941738.779927716, 948513.9036894421),
 (1940451.633629276, 949916.4071697283),
 (1941591.7473828683, 950232.0392019622),
 (1940840.6480232049, 951254.1858275363),
 (1942976.822807965, 949546.6784341566),
 (1942761.3573055407, 948746.4391310903),
 (1942464.6942925751, 949376.0300494421),
 (1942467.0726143331, 947839.0351924744),
 (1941549.584488726, 954010.1019579112),
 (1942548.774229721, 955490.7272109156),
 (1942387.8577742297, 954711.9192753212),
 (1942242.6530853626, 955866.3698388498),
 (1943917.6639786712, 954958.4107710336),
 (1943563.6799844103, 954977.7348916397),
 (1941056.4341154383, 959622.1625268542),
 (1941178.481059938, 958339.1829970246),
 (1945259.9772004508, 956287.5751948032),
 (1945988.1907873936, 957242.8076956422),
 (1944895.335775065, 957181.0275301308),
 (1944847.4492115504, 955511.6819052522),
 (1944237.2147503342, 956002.0588206801),
 (1945445.18854503, 957726.3423691964),
 (1943129.4846309875, 957519.3268727991),
 (1943445.1378111285, 958195.801821165),
 (1942513.5749643173, 957067.5430025104),
 (1944623.1515072887, 957955.6219895241),
 (1940119.7334263078, 960626.8519905879),
 (1943811.565355067, 958918.15250314),
 (1943879.3310702494, 960143.5112740042),
 (1943349.4727048634, 962416.4335191436),
 (1943172.9473370286, 962098.6311723894),
 (1941867.5816703674, 960542.7211540655),
 (1942947.610215014, 962249.5715899202),
 (1947222.6519823652, 960623.5861319463),
 (1945901.339926442, 961530.1780514191),
 (1945558.7249089275, 960065.1789499952),
 (1943568.1659873691, 961011.5964078723),
 (1944565.3471221894, 961671.2519376472),
 (1944322.8450102853, 961114.0331188637),
 (1946987.5861584842, 958025.4094672747),
 (1945606.5444163512, 958515.0382458523),
 (1946248.5036357793, 959291.5032353237),
 (1947582.889102046, 958632.7136318448),
 (1940856.8847147534, 965428.7442025659),
 (1943418.7675447671, 963734.7847160684),
 (1942447.0706105053, 963632.5902625946),
 (1942926.4759745228, 965084.2453421217),
 (1943146.711733763, 959376.9018836502),
 (1942810.9676557826, 960002.8537810479),
 (1945622.2299357476, 963823.873971155),
 (1945773.9998232624, 964345.527223334),
 (1945065.955686682, 962596.9052854145),
 (1945126.8980548093, 963476.6930161336),
 (1946523.5148009935, 965937.0010909854),
 (1946501.2793349056, 965983.4117886616),
 (1948527.551710627, 966793.7678449426),
 (1947477.0414865084, 966331.8003384926),
 (1944945.1906383762, 965708.4195754384),
 (1944547.59532202, 966309.39411404),
 (1944757.6278644938, 965272.679059893),
 (1944600.3929378497, 964176.3779197185),
 (1944082.8688237667, 965168.2819132842),
 (1944017.0679290576, 967228.4203865284),
 (1943688.3798720764, 966651.5658459059),
 (1944950.240773853, 968312.4221973668),
 (1945119.042055022, 967742.9124600114),
 (1942775.855534776, 967728.9630924147),
 (1942222.010872606, 968636.8875439905),
 (1945505.8291202674, 966951.544141833),
 (1945344.781556119, 962989.243542536),
 (1945583.7728774054, 967309.0553951894),
 (1944621.9536550918, 967265.5625576312),
 (1943864.4448288444, 968567.200759449),
 (1943562.211860385, 968972.9445495264),
 (1944713.4740996994, 968120.4589008436),
 (1944713.4740996994, 968120.4589008436),
 (1949799.65275631, 968919.9687258885),
 (1949933.7500569213, 967132.467635677),
 (1950525.7211980354, 969169.3028935761),
 (1950985.858360092, 970548.2404105642),
 (1950021.2450552767, 970623.2751643693),
 (1948630.9427399847, 968934.6994786214),
 (1946844.1817384833, 968108.7351659017),
 (1947826.779814256, 968605.2682452908),
 (1949814.7563870675, 967592.4712320425),
 (1950128.1137742088, 967273.6664144043),
 (1950380.8904897587, 968465.0403867911),
 (1947495.9796905417, 967058.538436754),
 (1947921.0278591136, 967307.7770193663),
 (1947042.623992449, 967692.0436552811),
 (1949387.6513207175, 968010.5936433771),
 (1950262.4088239986, 967356.7933383913),
 (1948669.2854081572, 967442.9193460506),
 (1951475.249217575, 971391.6908155383)]

In [ ]:
df_utmk = pd.DataFrame(list_utmk)
df_utmk.columns = ['위도utmk', '경도utmk']
df_utmk

           위도utmk         경도utmk
0    1.953680e+06  953451.030567
1    1.952806e+06  953286.588072
2    1.952190e+06  955056.678912
3    1.953774e+06  954435.679506
4    1.953223e+06  954699.580385
..            ...            ...
419  1.947043e+06  967692.043655
420  1.949388e+06  968010.593643
421  1.950262e+06  967356.793338
422  1.948669e+06  967442.919346
423  1.951475e+06  971391.690816

[424 rows x 2 columns]

In [ ]:
main = pd.concat([df, df_utmk], axis=1)
main

,시설명,주소,위도,경도,위도utmk,경도utmk
0,청운효자동 주민센터,서울특별시 종로구 자하문로 92,37.5840835,126.9706357,1.953680e+06,953451.030567
1,사직동 주민센터,서울특별시 종로구 사직로9길 1,37.576191449999996,126.96882915,1.952806e+06,953286.588072
2,종로1-4가동 주민센터,서울특별시 종로구 종로17길 8,37.5707276,126.9889123,1.952190e+06,955056.678912
3,삼청동 주민센터,서울특별시 종로구 삼청로 107,37.5849793,126.98178162729107,1.953774e+06,954435.679506
4,가회동 주민센터,서울특별시 종로구 북촌로 35,37.58002545,126.98480464831948,1.953223e+06,954699.580385
...,...,...,...,...,...,...
419,성내3동 주민센터,서울특별시 강동구 강동대로53길 76,37.5248662,127.1322197,1.947043e+06,967692.043655
420,천호1동 주민센터,서울특별시 강동구 구천면로42길 59,37.5460139,127.1357223,1.949388e+06,968010.593643
421,천호2동 주민센터,서울특별시 강동구 올림픽로 698,37.5538754,127.1282822,1.950262e+06,967356.793338
422,천호3동 주민센터,서울특별시 강동구 진황도로23길 7,37.5395191,127.1293281,1.948669e+06,967442.919346
423,강일동 주민센터,서울특별시 강동구 아리수로93길 9-14,37.5649416,127.1739152,1.951475e+06,971391.690816

In [ ]:
main.to_csv('/content/drive/MyDrive/PROJECT_senior it support center/데이터/main_utmk.csv')